### PR TITLE
Initial copy of stuff from the other two repos

### PR DESCRIPTION
**Pull request by myobie**

### CODE REVIEW

**Comment by myobie** [comment]
OK, I got it where express will boot and I stubbed out the integration points between the different pieces. I'll have a separate PR for the actual storage logic and then the rest of the api routes.

**Comment by bmuller** [comment]
Looks like there's a conflict.  Also - I've got a bin file for the `climate` command (so `climate serve` can be used to start the server, for instance).  Any items in the package.json scripts area should probably just call that directly - if those are needed at all (other than `test`)

**Comment by myobie** [comment]
Locally `standard` doesn't show any problems, but that is why Travis failed.

I will take care of the package.json problem.

**Comment by myobie** [comment]
OK, I fixed the conflict. 

Yeah, the npm script for serve was just a workaround while you were making the binary, so we should remove it.

**Pull request merged**
